# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Docfriends 기술 블로그"

writer:
  defaultImage: "/assets/images/member/defaultProfile.png"

writers:
  - member:
      id: "TejPak"
      url: "https://github.com/TejNote"
      image: "/assets/images/member/leaf9016.png"
      name: "박준걸"
  - member:
      id: "pikachu987"
      url: "https://github.com/pikachu987"
      image: "/assets/images/member/pikachu987.png"
      name: "김관호"
  - member:
      id: "ddalam"
      url: "https://github.com/ddalam"
      image: "/assets/images/member/ddalam.png"
      name: "최다영"
  - member:
      id: "zehye"
      url: "https://github.com/zehye"
      image: "/assets/images/member/zehye.jpeg"
      name: "박지혜"
  - member:
      id: "syh8088"
      url: "https://github.com/syh8088"
      image: "/assets/images/member/syh8088.png"
      name: "서양훈"
author:
  facebook:         groups/docfriends/
  youtubeUser:      Docairs
  github:           Docfriends
  email:            apps@docfriends.com

copyright:
  year:             2018
  name:             Docfriends

# Google-analytics
google-analytics:
  id:               "UA-131153272-1"

# Disqus
disqus:
  id:               "devstrory"

# URL
url:                "https://docfriends.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "/DevStrory" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Post"
    url:            "/"
  - name:           "Member"
    url:            "/member"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/Docfriends"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
